# NLP 2026
# Lab 3: Classification and BERT

Have you ever read a movie review and wondered:

```“Is this review actually positive or negative?” 🤔```

In this lab, you will build your own sentiment analysis tool using Natural Language Processing (NLP)! Your goal is to automatically classify movie reviews into one of two categories:

✅ Positive

❌ Negative

We will approach this as a binary classification task and you will experiment with increasingly powerful methods — from classic machine learning to modern neural networks based on transformers 🚀

### 🎯 Learning Goals ###

By completing this lab, you should be able to:

- Formulate sentiment analysis as a binary classification problem

- Design and evaluate hand-crafted text features

- Implement a Bag-of-Words representation

- Apply and evaluate Logistic Regression and alternative classifiers

- Understand how BERT tokenization and embeddings work

- Extract sentence representations using: ```CLS``` token, mean token pooling

- Compare classical ML and transformer-based methods

- Critically analyze evaluation metrics beyond accuracy 📊



### Score breakdown

| Exercise            | Points |
|---------------------|--------|
| [Exercise 1](#e1)   | 1      |
| [Exercise 2](#e2)   | 5      |
| [Exercise 3](#e3)   | 5      |
| [Exercise 4](#e4)   | 5      |
| [Exercise 5](#e5)   | 5      |
| [Exercise 6](#e6)   | 5      |
| [Exercise 7](#e7)   | 3      |
| [Exercise 8](#e8)   | 6      |
| [Exercise 9](#e9)   | 5      |
| [Exercise 10](#e10) | 5      |
| [Exercise 12](#e12) | 5      |
| [Exercise 13](#e13) | 10     |
| Total               | 60     |

This score will be scaled down to 0.6 and that will be your final lab score.

### 📌 **Instructions for Delivery** (📅 **Deadline: 23/Feb 18:00**, 🎭 *wildcards possible*)

✅ **Submission Requirements**
+ 📄 You need to submit a **notebook** 📓 with the code, appropriate comments and figures in all questions. Make sure to have a mix of code (some explanations needed if not clear what you implement), figures to support the answers or your claims and proper amount of text to explain your reasoning, answer etc.
+ ⚡ Make sure that **all cells are executed properly** ⚙️ and that **all figures/results/plots** 📊 you include in the report are also visible in your **executed notebook**.
+ You can work on Google Collab (or other environments), but you need to make sure that your delivered notebook is executed properly.

✅ **Collaboration & Integrity**
+ 🗣️ While you may **discuss** the lab with others, you must **write your solutions with your group only**. If you **discuss specific tasks** with others, please **include their names** below.
+ 📜 **Honor Code applies** to this lab. For more details, check **Syllabus §7.2** ⚖️.
+ 📢 **Mandatory Disclosure**:
   - Any **websites** 🌐 (e.g., **Stack Overflow** 💡) or **other resources** used must be **listed and disclosed**.
   - Any **GenAI tools** 🤖 (e.g., **ChatGPT**) used must be **explicitly mentioned**.
   - 🚨 **Failure to disclose these resources is a violation of academic integrity**. See **Syllabus §7.3** for details.

## 0. Setup

We first install the scikit-learn library [Scikit-learn](https://scikit-learn.org/stable/). We will use its classification models.

In [1]:
# pip install -U scikit-learn

We will need [PyTorch](https://pytorch.org/) installed. It is a very popular deep learning library that offers modularized versions of many of the sequence models we discussed in class. It's an important tool that you may want to practice further if you want to dive deeper into NLP, since much of the current academic and industrial research uses it.

Some resources to look further are given below.

* [Documentation](https://pytorch.org/docs/stable/index.html) (We will need this soon)

* [Installation Instructions](https://pytorch.org/get-started/locally/)

* [Quickstart Tutorial](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html)

The cell below should install the library:

In [1]:
# pip install torch torchvision

The last bit we need is the huggingface transformers library (here is the documentation [https://huggingface.co/docs/transformers/en/index](https://huggingface.co/docs/transformers/en/index)). Transformers are one of the most influential architectures in handling sequences (not only in language). As we discussed in lectures, they excel at taking into account context (which is the salt-and-pepper of NLP) with mechansisms such as self-attetion, which allows them to weigh the importance of different words in a sentence. If you want to know more, revisit the course material (slides and textbook).

We already used huggingface datasets in previous labs and huggingface transformers integrates nicely with that. Apart from the ease of use, huggingface is also providing pre-trained models of different kinds. The list can be found [here](https://huggingface.co/models) ([https://huggingface.co/models](https://huggingface.co/models)). The following line should be enough to install huggingface transformers library:

In [2]:
# pip install transformers

Here, we import the libraries:

In [3]:
import re
from collections import Counter

import datasets
import numpy as np
import torch
import tqdm
import transformers
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from torch.utils.data.dataloader import DataLoader

## 1. Loading the Dataset

We will work with the IMDB dataset [https://huggingface.co/datasets/stanfordnlp/imdb](https://huggingface.co/datasets/stanfordnlp/imdb). It contains the reviews and a label that indicates whether the review is positive or not (the neutral reviews have been filtered out). You can read the paper [here](https://aclanthology.org/P11-1015/).

In [4]:
dataset = datasets.load_dataset('stanfordnlp/imdb', split=['train', 'test'])
print(dataset)

[Dataset({
    features: ['text', 'label'],
    num_rows: 25000
}), Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})]


Notice that the dataset has been loaded as a list of two datasets. They are the `train` and `test` splits that we asked for.
We will use the validation subset to tune the parameters. So, let's split the `train` subset and create a `DatasetDict` object:

In [5]:
train_valid_split = dataset[0].train_test_split(5000)
dataset = datasets.DatasetDict({
    'train': train_valid_split['train'].shuffle(),
    'validation': train_valid_split['test'].shuffle(),
    'test': dataset[1].shuffle(),
})
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 20000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
})


We can print several examples from the `train` dataset:

In [6]:
for i in range(5):
    print('i', i)
    print(dataset['train'][i]['text'])
    print(dataset['train'][i]['label'])
    print()

i 0
OK, I have been a huge fan of the Black for a long time and was DISGUSTED after seeing this film. Let's name the problems...First this film has much of the same crew that the first two had. It has also been called the PREQUEL to the original Black Stallion. Why is it that they can't get Shetan's dam's name correct or her color?? In The Black Stallion Returns, we learn the Sagr was the Black's CHESTNUT mother and in this film she is a gray mare name Jenny?!?!?!?!? WTF? And it's set in Africa in 1946 and 1947...I could be wrong but the first one was set in the 1940's as well when the ship wrecks. Time line doesn't sound quite right to me. Also, as a goof, there is a friesian in the beginning of the movie that is supposed to be Shetan's father...upon further notice it appears to be a gelding. Ben Ishaak is the only character that remained to even make this film appear to be related to the previous two in any way. Might be a cute family film to some but it's my biggest movie disappoint

Let's extract the labels from the dataset. We will use them to train and evaluate our classifiers.

In [7]:
y_train = dataset['train']['label']
print(y_train)
y_valid = dataset['validation']['label']
print(y_valid)

Column([0, 0, 1, 0, 0, ...])
Column([1, 0, 0, 0, 1, ...])


<a name='e1'></a>
#### Exercise 1: Cleaning the text

(1p) In this exercise you should clean the text in the dataset. This is the same step we saw in the previous labs.

If you think this step is not necessary in this use case, you can skip this step, but make sure to justify your decision.

In [8]:
def clean(text):
    """
    Cleans the text 
    Args:
        text: a string that will be cleaned

    Returns: the cleaned text

    """

    # Empty text
    if text == '':
        return text

    ### YOUR CODE HERE
    
    # Remove HTML
    text = re.sub(r'<.*?>', '', text)

    # Lowercase
    text = text.lower()

    # Expand contractions
    text = re.sub(r"n't\b", " not", text)

    # Normalize repeated characters
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)

    # Negation handling
    text = re.sub(r'\bnot\s+(\w+)', r'not_\1', text)

    # Remove punctuation but keep underscore for negation handling
    # text = re.sub(r'[^\w\s_]', '', text)

    # Collapse spaces
    text = re.sub(r'\s+', ' ', text)
    
    # Minimal stopwords
    stop_words = set(['a', 'an', 'the'])
    words = [w for w in text.split() if w not in stop_words]
    text = ' '.join(words)
    
    text = text.strip()


    ### YOUR CODE ENDS HERE

    return text


def clean_example(example):
    """
    Applies the clean() function to the example from the Dataset
    Args:
        example: an example from the Dataset

    Returns: update example with cleaned 'text' column

    """
    example['text'] = clean(example['text'])
    return example


dataset = dataset.map(clean_example, desc="Cleaning")
print(dataset)

Cleaning:   0%|          | 0/20000 [00:00<?, ? examples/s]

Cleaning:   0%|          | 0/5000 [00:00<?, ? examples/s]

Cleaning:   0%|          | 0/25000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 20000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
})


In [9]:
def show_cleaning_example(text):
    print("before: ",text)
    print("after: ", clean(text))

example = "This movie is NOT good!!! I don't like it at all. <br /> It was soooo boring."

show_cleaning_example(example)

before:  This movie is NOT good!!! I don't like it at all. <br /> It was soooo boring.
after:  this movie is not_good!! i do not_like it at all. it was soo boring.


## 2. Hand-crafted Features

<a name='e2'></a>
#### Exercise 2: Hand-crafted features

(5p) Write your own hand-crafted feature extraction function. Include at least these types of features:
- length of the text,
- number of different punctuation characters,
- number of positive and negative words.

In [10]:
######################################## V0 ################################################## Vanilla
### YOUR CODE HERE
# you can define the positive and negative words here

positive_words = set(['good','amazing','great','excellent','wonderful','thrilling','exciting','nice', 'best'])
negative_words = set(['bad', 'horrible', 'terrible', 'boring', 'worst', 'awful'])
punctuation_set = {".", "!", "?", ",", ";"}


def calculate_features(text):
    features = []
    ### YOUR CODE HERE
    unique_punctuation_count = 0
    positive_word_count = 0
    negative_word_count = 0

    words = text.split()

    word_count = len(words)

    for word in words: 
        if word in positive_words:
            positive_word_count += 1
        if word in negative_words:
            negative_word_count += 1
    
    found_punctuation = set()

    for char in text:
        if char in punctuation_set:
            found_punctuation.add(char)

    unique_punctuation_count = len(found_punctuation)
        
    features = [
        word_count,
        unique_punctuation_count,
        positive_word_count,
        negative_word_count
    ]

    ### YOUR CODE ENDS HERE
    return np.array(features, dtype=float)


### YOUR CODE ENDS HERE

In [11]:
######################### V1 ###################################
### YOUR CODE HERE
# you can define the positive and negative words here

positive_words = set(['good','amazing','great','excellent','wonderful','thrilling','exciting','nice', 'best'])
negative_words = set(['bad', 'horrible', 'terrible', 'boring', 'worst', 'awful'])
punctuation_set = {".", "!", "?", ",", ";"}


def calculate_features_v1(text):
    features = []
    ### YOUR CODE HERE
    unique_punctuation_count = 0
    positive_word_count = 0
    negative_word_count = 0

    words = text.split()

    word_count = len(words)

    for word in words: 
        if word in positive_words:
            positive_word_count += 1
        if word in negative_words:
            negative_word_count += 1
    
    found_punctuation = set()

    for char in text:
        if char in punctuation_set:
            found_punctuation.add(char)

    unique_punctuation_count = len(found_punctuation)
        
    features = [
        word_count,
        unique_punctuation_count,
        positive_word_count,
        negative_word_count
    ]

    ### YOUR CODE ENDS HERE
    return np.array(features, dtype=float)


### YOUR CODE ENDS HERE

In [12]:
############################ V2 #####################################
# New: Added many new positive and negative words
positive_words_V2 = set([
    "good","great","amazing","excellent","wonderful","best","love","loved","lovely",
    "awesome","fantastic","brilliant","superb","outstanding","perfect","enjoy","enjoyed",
    "fun","funny","hilarious","charming","beautiful","moving","touching","heartwarming",
    "impressive","solid","strong","well","wellmade","masterpiece","recommend","recommended",
    "favorite","favourite","satisfying","pleasant","clever","smart","engaging","thrilling",
    "exciting","delightful","captivating","incredible","remarkable","refreshing","fine"
])

negative_words_V2 = set([
    "bad","terrible","horrible","awful","worst","boring","hate","hated","dull","stupid",
    "ridiculous","waste","wasted","disappointing","disappointed","disaster","poor",
    "weak","forgettable","mess","confusing","annoying","irritating","painful","predictable",
    "cliche","cliched","lame","pathetic","mediocre","unfunny","nonsense","pointless",
    "garbage","trash","crap","ugly","flawed","slow","tedious","overrated","unwatchable",
    "fails","failed","failure","nasty","gross","insulting"
])

punctuation_set = {".", "!", "?", ",", ";"}


def calculate_features_v2(text):
    features = []
    unique_punctuation_count = 0
    positive_word_count = 0
    negative_word_count = 0
    
    negated_token_count = 0      # New: count tokens like not_good, not_funny
    negated_pos_count = 0        # New: count not_ + positive (e.g., not_good)
    negated_neg_count = 0        # New: count not_ + negative (e.g., not_awful)

    words = text.split()

    word_count = len(words)

    for word in words: 
        if word.startswith("not_"):
            negated_token_count += 1
            base = word[4:]
            if base in positive_words_V2:
                negated_pos_count += 1
            if base in negative_words_V2:
                negated_neg_count += 1
            continue

        if word in positive_words_V2:
            positive_word_count += 1
        if word in negative_words_V2:
            negative_word_count += 1
    
    found_punctuation = set()

    for char in text:
        if char in punctuation_set:
            found_punctuation.add(char)

    unique_punctuation_count = len(found_punctuation)
    
    sentiment_difference = positive_word_count - negative_word_count

    denominator = max(word_count, 1)
    positive_ratio = positive_word_count / denominator
    negative_ratio = negative_word_count / denominator
    # New: Ratio of negated tokens: 
    negated_ratio = negated_token_count / denominator

    features = [
        word_count,
        unique_punctuation_count,
        positive_word_count,
        negative_word_count,
        sentiment_difference,
        positive_ratio,
        negative_ratio,
        negated_token_count,     # New
        negated_pos_count,       # New
        negated_neg_count,       # New
        negated_ratio            # New
    ]

    return np.array(features, dtype=float)


In [13]:
################################# V3 #######################################
positive_words_V2 = set([
    "good","great","amazing","excellent","wonderful","best","love","loved","lovely",
    "awesome","fantastic","brilliant","superb","outstanding","perfect","enjoy","enjoyed",
    "fun","funny","hilarious","charming","beautiful","moving","touching","heartwarming",
    "impressive","solid","strong","well","wellmade","masterpiece","recommend","recommended",
    "favorite","favourite","satisfying","pleasant","clever","smart","engaging","thrilling",
    "exciting","delightful","captivating","incredible","remarkable","refreshing","fine"
])

negative_words_V2 = set([
    "bad","terrible","horrible","awful","worst","boring","hate","hated","dull","stupid",
    "ridiculous","waste","wasted","disappointing","disappointed","disaster","poor",
    "weak","forgettable","mess","confusing","annoying","irritating","painful","predictable",
    "cliche","cliched","lame","pathetic","mediocre","unfunny","nonsense","pointless",
    "garbage","trash","crap","ugly","flawed","slow","tedious","overrated","unwatchable",
    "fails","failed","failure","nasty","gross","insulting"
])

punctuation_set = {".", "!", "?", ",", ";"}


def calculate_features_v3(text):
    features = []
    unique_punctuation_count = 0
    positive_word_count = 0
    negative_word_count = 0
    
    negated_token_count = 0      
    negated_pos_count = 0        
    negated_neg_count = 0    

    # New: Count exclamation and Question marks
    exclamation_counter = text.count("!")
    question_counter = text.count("?")
    
    # New: Check if there are multiple question or exclamation marks
    has_multi_exclam = 0
    has_multi_question = 0
    if "!!" in text:
        has_multi_exclam = 1
    if "??" in text:
        has_multi_question = 1

    words = text.split()

    word_count = len(words)

    for word in words: 
        if word.startswith("not_"):
            negated_token_count += 1
            base = word[4:]
            if base in positive_words_V2:
                negated_pos_count += 1
            if base in negative_words_V2:
                negated_neg_count += 1
            continue

        if word in positive_words_V2:
            positive_word_count += 1
        if word in negative_words_V2:
            negative_word_count += 1
    
    found_punctuation = set()

    for char in text:
        if char in punctuation_set:
            found_punctuation.add(char)

    unique_punctuation_count = len(found_punctuation)
    
    sentiment_difference = positive_word_count - negative_word_count

    denominator = max(word_count, 1)
    positive_ratio = positive_word_count / denominator
    negative_ratio = negative_word_count / denominator
    # New: Ratio of negated tokens: 
    negated_ratio = negated_token_count / denominator

    features = [
        word_count,
        unique_punctuation_count,
        positive_word_count,
        negative_word_count,
        sentiment_difference,
        positive_ratio,
        negative_ratio,
        negated_token_count,     
        negated_pos_count,       
        negated_neg_count,       
        negated_ratio,
        exclamation_counter, #New
        question_counter, #New
        has_multi_question, #New
        has_multi_exclam #New           
    ]

    return np.array(features, dtype=float)


In [14]:
############################ V4 ################################# PS. Pythonic code style is different since it was implemented by a different group member unlike the preceeding versions
### YOUR CODE HERE

from collections import Counter
# NEW : Use of string library to import all types of punctuation symbols (full coverage)
import string
punctuation = set(string.punctuation)

def calculate_features_v4(text):
    features = []

    # ensure text is a string
    if not isinstance(text, str):
        text = str(text)

    # Tokenize using regex (keeps underscores from negation: not_word)
    words = re.findall(r"\b[\w_]+\b", text.lower())
    word_count = len(words)
    features.append(word_count)

    # distinct punctuation characters in raw text
    punct_counts = set(c for c in text if c in punctuation)
    features.append(len(punct_counts))

    # count positive / negative words (compare base word, strip leading 'not_' if present)
    def base(w):
        return w[4:] if w.startswith("not_") else w

    num_positive = sum(1 for w in words if base(w) in positive_words_V2) # using the previously defined words corpora
    num_negative = sum(1 for w in words if base(w) in negative_words_V2)
    features.append(num_positive)
    features.append(num_negative)

    # sentimental variance 
    sentimental_diff = (num_positive - num_negative)
    denominator = max(word_count, 1)
    pos_ratio = num_positive / denominator
    neg_ratio = num_negative / denominator
    log_odds = np.log((num_positive+1)/(num_negative+1))

    # negation counts (tokens starting with 'not_')
    num_negations = sum(1 for w in words if w.startswith("not_"))
    num_positive_negations = sum(1 for w in words if w.startswith("not_") and w[4:] in positive_words_V2)
    num_negative_negations = sum(1 for w in words if w.startswith("not_") and w[4:] in negative_words_V2)
    negation_ratio = num_negations / denominator

    # exaggeration symbols from raw text
    count_exclamations = text.count("!")
    count_questions = text.count("?")
    has_multiple_exclamations = int(re.search(r'!{2,}', text) is not None)
    has_multiple_questions = int(re.search(r'\?{2,}', text) is not None)

    features.extend([
        sentimental_diff, 
        pos_ratio, 
        neg_ratio,
        num_negations,
        num_positive_negations,
        num_negative_negations,
        negation_ratio,
        count_exclamations, 
        count_questions, 
        has_multiple_questions, 
        has_multiple_exclamations, 
        log_odds # NEW - log odds for measuring quantified sentimental difference
    ])

    return np.array(features, dtype=float)

### YOUR CODE ENDS HERE

The function below will apply your feature extraction implementation to a specified dataset.

In [15]:
############################ V5 ################################# PS. Pythonic code style is different since it was implemented by a different group member unlike the preceeding versions (V1,2,3)
### YOUR CODE HERE

from collections import Counter
# --------------------------
import string
punctuation = set(string.punctuation)
# NEW : Use of NLTK corpora of positive and negative words for an even larger coverage of words
# define the positive and negative words here
import nltk
from nltk.corpus import opinion_lexicon
nltk.download('opinion_lexicon')
pos_words = set(opinion_lexicon.positive())
neg_words = set(opinion_lexicon.negative())
# -------------------------------

def calculate_features_v5(text):
    features = []

    # ensure text is a string
    if not isinstance(text, str):
        text = str(text)

    # Tokenize using regex (keeps underscores from negation: not_word)
    words = re.findall(r"\b[\w_]+\b", text.lower())
    word_count = len(words)
    features.append(word_count)

    # distinct punctuation characters in raw text
    punct_counts = set(c for c in text if c in punctuation)
    features.append(len(punct_counts))

    # count positive / negative words (compare base word, strip leading 'not_' if present)
    def base(w):
        return w[4:] if w.startswith("not_") else w

    num_positive = sum(1 for w in words if base(w) in pos_words)
    num_negative = sum(1 for w in words if base(w) in neg_words)
    features.append(num_positive)
    features.append(num_negative)

    # sentimental variance 
    sentimental_diff = (num_positive - num_negative)
    denominator = max(word_count, 1)
    pos_ratio = num_positive / denominator
    neg_ratio = num_negative / denominator
    log_odds = np.log((num_positive+1)/(num_negative+1))

    # negation counts (tokens starting with 'not_')
    num_negations = sum(1 for w in words if w.startswith("not_"))
    num_positive_negations = sum(1 for w in words if w.startswith("not_") and w[4:] in pos_words)
    num_negative_negations = sum(1 for w in words if w.startswith("not_") and w[4:] in neg_words)
    negation_ratio = num_negations / denominator

    # exaggeration symbols from raw text
    count_exclamations = text.count("!")
    count_questions = text.count("?")
    has_multiple_exclamations = int(re.search(r'!{2,}', text) is not None)
    has_multiple_questions = int(re.search(r'\?{2,}', text) is not None)

    features.extend([
        sentimental_diff, 
        pos_ratio, 
        neg_ratio,
        num_negations,
        num_positive_negations,
        num_negative_negations,
        negation_ratio,
        count_exclamations, 
        count_questions, 
        has_multiple_questions, 
        has_multiple_exclamations, 
        log_odds 
    ])

    return np.array(features, dtype=float)

### YOUR CODE ENDS HERE

[nltk_data] Downloading package opinion_lexicon to
[nltk_data]     C:\Users\omern\AppData\Roaming\nltk_data...
[nltk_data]   Package opinion_lexicon is already up-to-date!


In [16]:
def calculate_features_dataset(dataset, features_fn):
    all_features = []
    for e in tqdm.tqdm(dataset, desc='Extracting features'):
        text = e['text']
        features = features_fn(text)
        all_features.append(features)
    all_features = np.array(all_features, dtype=float)
    return all_features

And we can obtain the features for the `train` and `validation` splits. Later you will need to do the same for the `test` subset.

In [17]:
X_train = calculate_features_dataset(dataset['train'], calculate_features)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features)

Extracting features: 100%|██████████| 5000/5000 [00:00<00:00, 13980.31it/s]


### 2.1 Classification

In this section, we will create and train a logistic regression classifier. We will train it on the `train` subset and evaluate on the `validation` split. Later, you will do a final comparison between methods on the `test` subset, but it is important to avoid it when tuning the methods.

In [18]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

Let's check the performance on the training data:

In [19]:
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))

Features results: train
0.6795


... and the validation dataset:

In [20]:
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))

Features results: validation
0.6914


<a name='e3'></a>
#### Exercise 3: Improving the features

(5p) Iteratively improve your hand-crafted features. Think about what information from the review might be useful for to predict the rating a person gave to the particular movie. You can also look into the expected format (or range) of features for the classifier.

Document the steps you tried (even if unsuccessful) and how they influenced the metrics. Try at least 3 modifications from your original implementation.

In [21]:
### YOUR CODE HERE
'''
Pipeline for V1
'''
X_train = calculate_features_dataset(dataset['train'], calculate_features_v1)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features_v1)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))
### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:00<00:00, 15768.29it/s]


Features results: train
0.6795
Features results: validation
0.6914


In [22]:
### YOUR CODE HERE
'''
Pipeline for V2
'''
X_train = calculate_features_dataset(dataset['train'], calculate_features_v2)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features_v2)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))
### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:00<00:00, 12356.01it/s]


Features results: train
0.76975
Features results: validation
0.7798


In [23]:
### YOUR CODE HERE
'''
Pipeline for V3
'''
X_train = calculate_features_dataset(dataset['train'], calculate_features_v3)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features_v3)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))
### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:00<00:00, 11589.84it/s]


Features results: train
0.7742
Features results: validation
0.7872


--- YOUR ANSWERS HERE

In [24]:

### YOUR CODE HERE
'''
Pipeline for V4
'''
X_train = calculate_features_dataset(dataset['train'], calculate_features_v4)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features_v4)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))
### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:01<00:00, 4573.90it/s]
c:\Users\omern\miniconda3\envs\nlplab2026\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Features results: train
0.80015
Features results: validation
0.8048


In [25]:
### YOUR CODE HERE
'''
Pipeline for V5
'''
X_train = calculate_features_dataset(dataset['train'], calculate_features_v5)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features_v5)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))
### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:01<00:00, 4475.97it/s]
c:\Users\omern\miniconda3\envs\nlplab2026\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Features results: train
0.7521
Features results: validation
0.7584



#### First run (used standard version): 
Train set: 0.70365. 

Validation set: 0.702.

In this run we used the very first version of the extraction function. The results are better than random guessing but can definetelely be improved.

#### Second run (used V1): 
Train set: 0.7037

Validation set: 0.7018

This approach was rather unsuccesfull. The changes made were adding a sentiment difference and normalized ratio of positive and negative words. However these changes did not significantly improve the performance. This is likely because Logistic Regression can already learn linear combinations of positive and negative word counts. 

#### Third run (used V2): 
Train set: 0.7942

Validation set: 0.7892

Here we can see significant improvement in the accuracy score for both the validation and train set. The changes made in the V2 version were primarily adding more positve and negative words, as well as accounting for negated tokens. In our cleaning functions we turn negations into one token by connecting words like "not good" into one token like "not_good". In the v2 version we count these negated tokens as well as the ratio of negated tokens and add them to the feature vector. Adding new positive and negative words led to more reviews triggering positive and negative matches which drastically improved the coverage. Furthermore the negation specific features introduced a completely new signal to the classifier, likely also positively affecting the performance. 

#### Fourth run (used V3): 
Train set: 0.7943

Validation set: 0.789

This approach was rather unsuccesfull. The changes made were adding counts of exclamation and question marks, as well as capturing strings of multiple exclamation and question marks. These changes did not have a positive or negative impact, which indicates that the most sentiment is already captured by words.

#### Fifth run (used V4):
Train set: 0.8018

Validation set: 0.798

This approach amazingly outpeformed V3. This version refactors V3, tokenizes the text by using `re.findall(r"\b[\w_]+\b")` to preserve the `not_`. This version also introduces a larger corpus that covers all punctuation symbols (imported from `string`). V4 also adds a new feature: log-odds that proposes another way to determine the difference between the 2 sentiments (positive and negative). Overall is more robust and written in a pythonic way that follows the recommended principles.

#### Sixth run (used V5):
Train set: 0.7534

Validation set: 0.7548

This version is inferior to V4. The only reason that may be is because it adapts larger corpora of positive and negative words from `nltk`. This is shown to result in noisier lexicon containing ambiguous words leading to more false matches thus reducing overall accuracy.



<a name='e4'></a>
#### Exercise 4: Improving the evaluation

(5p) In the previous cells, we only looked at the accuracy of predictions. Investigate which other metrics might be better for our case. You can check the documentation of scikit-learn for evaluation metrics ([https://scikit-learn.org/stable/api/sklearn.metrics.html#classification-metrics](https://scikit-learn.org/stable/api/sklearn.metrics.html#classification-metrics)). Give reasons why the metrics you try can be more informative than raw accuracy score.

Decide which evaluation metric(s) is most suitable for our use-case and give reasons why. Test your features-based classifier and all further classifiers on that metric (apart from the accuracy score).

In [26]:
### YOUR CODE HERE
# We decided to add Precision, Recall, the F1 score and we compute a confusion matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix



X_train = calculate_features_dataset(dataset['train'], calculate_features_v4)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features_v4)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))
print('Features results: validation')
pred_valid = classifier.predict(X_valid)

print("Accuracy Score:")
print(accuracy_score(y_valid, pred_valid))

print("F1 Score:")
print(f1_score(y_valid, pred_valid))

print("Precision Score:")
print(precision_score(y_valid, pred_valid))

print("Recall Score:")
print(recall_score(y_valid, pred_valid))

print("Confusion Matrix:")
print(confusion_matrix(y_valid, pred_valid))

### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:01<00:00, 4568.59it/s]
c:\Users\omern\miniconda3\envs\nlplab2026\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Features results: train
0.80015
Features results: validation
Accuracy Score:
0.8048
F1 Score:
0.8076468269609776
Precision Score:
0.7966562986003111
Recall Score:
0.8189448441247003
Confusion Matrix:
[[1975  523]
 [ 453 2049]]


--- YOUR ANSWERS HERE
#### Answer Exercise 4 

We added the following metrics: **F1 Score, Precision, Recall, Confusion Matrix**

The reasons for adding each metric are presented in the following paragraph. Accuracy alone already provides a general overview of the model performance but cannot distinguish between different types of erros in classification. To also take into account the false positves and false negatives we decided to add precision and recall to seperatetly evaluate how reliable positive predictions are (precision) and how well the model detects actual positive reviews (recall). We also added the F1-score because it combines the precision and recall which makes it more informative than accuracy alone. The Confusion matrix simply provides an overview of the distribution of True Positives, True Negatives, False Positives and False Negatives.

Obtained Results: 

**Accuracy**: 0.7776

**F1 Score**: 0.7892342683851402

**Precision**: 0.7620790629575402

**Recall**: 0.8183962264150944

**Confusion Matrix**: TN = 1806, FP = 650, FN = 462, TP = 2082

One interesting observation is that **Recall > Precision**. The model detects most positive reviews as positive, indicated by the high recalll of about 81%. However this comes at the cost of predicting some negative reviews as positive. The confusion matrix confirms that the false positives occur more often than the false negatives (650 > 462) altough the dataset is balanced. This indicates a mild bias towards predicting positive. 

Another important observation is that **Recall > F1 score > Precision**. This behaviour is expected, as the F1 score represents the harmonic mean between the Precision and Recall. The F1 score balances the trade-off between detecting positive reviews and avoiding incorrect positive predictions. The relatively high F1 score indicates that the classifier achieves a good balance between identifying most positive reviews and limiting false positive predictions. 



## 3. Bag-of-Words Classifier

Similar to the previous lab, we will use the classic bag-of-words representation as one of our embeddings. While it is simple and does not preserve the positions of words, it gives our classifier a lot of useful information.

<a name='e5'></a>
#### Exercise 5: Implementing BOW

(5p) Implement the BOW. In this exercise, we do not give you a rigid structure, so you can conjure your own. The two things your code should produce is the `token_to_id` dictionary, and `bag_of_words()` function that accepts a list of tokens, and the `token_to_id` dictionary while generating the BOW representation as a numpy array.

In [27]:
#### YOUR CODE HERE

MAX_VOCAB_SIZE = 1_000

# The goal is to implement the `bag_of_words(tokens, token_to_id)` function similar to the previous lab.
# You might want to follow the steps:
# - tokenize the `text` column in the dataset,
# - extract the vocabulary from the tokens,
# - limit the vocabulary to `MAX_VOCAB_SIZE`,
# - calculate the `token_to_id` dictionary
# - implement the `bag_of_words(tokens, token_to_id)` function.
def tokenise(text):
    tokens = text.split()
    return tokens

dataset = dataset.map(lambda ex: {"tokens": tokenise(ex["text"])})
    
def build_vocab_counter():
    vocab_counter = Counter()
    for tokens in dataset["train"]["tokens"]:
        vocab_counter.update(tokens)
    return vocab_counter

def build_token_to_id(vocab: Counter, vocab_size: int):
    token_to_id = {}
    most_common_tokens = vocab.most_common(vocab_size)

    for index, (token, count) in enumerate(most_common_tokens):
        token_to_id[token] = index
    return token_to_id

def bag_of_words(tokens, token_to_id):
    """
    Creates a bag-of-words representation of the sentence
    Args:
        tokens: a list of tokens
        token_to_id: a dictionary mapping each word to an index in the vocabulary

    Returns:: a numpy array of size vocab_size with the counts of each word in the vocabulary
    """
    vocab_size = len(token_to_id)

    bow_vector = np.zeros(vocab_size, dtype=int)
    
    for token in tokens: 
        vocab_idx = token_to_id.get(token)
        if vocab_idx is not None: 
            bow_vector[vocab_idx] += 1

    return bow_vector

vocab = build_vocab_counter()
token_to_id = build_token_to_id(vocab, MAX_VOCAB_SIZE)



#### YOUR CODE ENDS HERE

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Here, we will use your implemented function to calculate the bag-of-words for each example in the `train` and `validation` subsets.

In [28]:
train_bows = []
for example in tqdm.tqdm(dataset['train'], desc='Calculating test BOWs'):
    train_bows.append(bag_of_words(example['tokens'], token_to_id))
train_bows = np.array(train_bows, dtype=float)

valid_bows = []
for example in tqdm.tqdm(dataset['validation'], desc='Calculating validation BOWs'):
    valid_bows.append(bag_of_words(example['tokens'], token_to_id))
valid_bows = np.array(valid_bows, dtype=float)

Calculating validation BOWs: 100%|██████████| 5000/5000 [00:00<00:00, 5255.74it/s]


Finally, we can train the classifier on the BOW representations and the labels in the `train` split.

In [29]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
print('Training classifier...')
classifier.fit(train_bows, y_train)

Training classifier...


LogisticRegression(max_iter=1000)

Let's evaluate the classifier:

In [30]:
print('BOW results: train')
pred_train = classifier.predict(train_bows)
print(accuracy_score(y_train, pred_train))

print('BOW results: validation')
pred_valid = classifier.predict(valid_bows)
print(accuracy_score(y_valid, pred_valid))

BOW results: train
0.86345
BOW results: validation
0.8344


<a name='e6'></a>
#### Exercise 6: Tuning the model

(5p) Try different values for the vocab size. Experiment with adding the hand-crafted features. Test the model on the evaluation metric of your choice (remember to use the validation split).

In [ ]:
#### YOUR CODE HERE

from sklearn.preprocessing import StandardScaler


def make_bow_matrix(split_name: str, token_to_id):
    bows = []
    for example in tqdm.tqdm(dataset[split_name], desc='Calculating BOWs'):
        bows.append(bag_of_words(example['tokens'], token_to_id))
    return np.array(bows, dtype=float)

def make_handcrafted_matrix(split_name):
    features = []
    for example in tqdm.tqdm(dataset[split_name], desc='Calculating Hand crafted features'):
        features.append(calculate_features_v4(example["text"]))
    return np.vstack(features).astype(float)

def run_experiment(vocab_size: int, use_handcrafted: bool):
    vocab = build_vocab_counter()
    token_to_id = build_token_to_id(vocab, vocab_size)

    X_train = make_bow_matrix("train", token_to_id)
    X_valid = make_bow_matrix("validation", token_to_id)

    if use_handcrafted:
        train_feats = make_handcrafted_matrix("train")
        valid_feats = make_handcrafted_matrix("validation")

        scaler = StandardScaler()
        train_feats_scaled = scaler.fit_transform(train_feats)
        valid_feats_scaled = scaler.transform(valid_feats)

        X_train = np.hstack([X_train, train_feats_scaled])
        X_valid = np.hstack([X_valid, valid_feats_scaled])

    classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
    classifier.fit(X_train, y_train)
    
    print('BOW results: train')
    pred_train = classifier.predict(X_train)

    print('BOW results: validation')
    pred_valid = classifier.predict(X_valid)

    results = {
        "vocab_size": vocab_size,
        "use_handcrafted": use_handcrafted,
        "train_acc": accuracy_score(y_train, pred_train),
        "valid_acc": accuracy_score(y_valid, pred_valid),
        "valid_f1": f1_score(y_valid, pred_valid),
        "valid_precision": precision_score(y_valid, pred_valid),
        "valid_recall": recall_score(y_valid, pred_valid),
        "confusion_matrix": confusion_matrix(y_valid, pred_valid)
    }
    
    return results

VOCAB_SIZES = [500, 1000, 1500, 2000, 5000, 10000]
all_results = []

for vs in VOCAB_SIZES:
    # BOW only
    r1 = run_experiment(vs, use_handcrafted=False)
    all_results.append(r1)

    # BOW + handcrafted
    r2 = run_experiment(vs, use_handcrafted=True)
    all_results.append(r2)

for r in all_results:
    tag = "BOW+HC" if r["use_handcrafted"] else "BOW"
    print(f"\n=== {tag} | vocab={r['vocab_size']} ===")
    print("Train acc:", r["train_acc"])
    print("Valid acc:", r["valid_acc"])
    print("Valid F1:", r["valid_f1"])
    print("Valid Precision:", r["valid_precision"])
    print("Valid Recall:", r["valid_recall"])
    print("Confusion Matrix:\n", r["confusion_matrix"])
#### YOUR CODE ENDS HERE

## 4. BERT Model

For the first part of this lab, we will be using a pre-trained BERT model from Huggingface, namely the [BERT Cased](https://huggingface.co/google-bert/bert-base-cased). You can read the original paper that introduced this model [here](https://aclanthology.org/N19-1423.pdf). This paper has been one of the most cited papers ever (currently having more than 100,000 citations).

We will specify the model name that can be found on the model's card on huggingface (revisit the first link). Make sure to check what other information Huggingface is offering (e.g. how to use the model, limitations, how to inference, etc.).

In [31]:
from optimum.intel import OVModelForFeatureExtraction
from transformers import AutoTokenizer
import openvino as ov

# Verify devices
core = ov.Core()
print("Available devices:", core.available_devices)

model_name = 'google-bert/bert-base-cased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load BERT with OpenVINO on GPU
model = OVModelForFeatureExtraction.from_pretrained(
    model_name,
    export=True,    # converts PyTorch → OpenVINO (first time only, then cached)
    device="GPU"    # your Intel Arc
)
print("Model ready!")


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\omern\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\omern\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\omern\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

ImportError: cannot import name 'OVModelForFeatureExtraction' from 'optimum.intel' (c:\Users\omern\miniconda3\envs\nlplab2026\Lib\site-packages\optimum\intel\__init__.py)

### 4.1 Tokenizer

The models on huggingface come with their own tokenizers. They are loaded separately from the models. We can use [AutoTokenizer](https://huggingface.co/docs/transformers/v4.40.2/en/model_doc/auto#transformers.AutoTokenizer)'s `from_pretrained()` method to load it.

Inspect the output: The loaded object is of `BertTokenizer` class. Check the documentation [here](https://huggingface.co/docs/transformers/en/model_doc/bert#transformers.BertTokenizer).

In [ ]:
tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)
print(tokenizer)

BertTokenizer(name_or_path='google-bert/bert-base-cased', vocab_size=28996, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)


Next, let's see how we can use it to tokenize some text.

In [34]:
print(dataset['test'][0]['text'])
tokenized = tokenizer(dataset['test'][0]['text'], padding=True, return_tensors='pt')
print("---")
print(type(tokenized))
print("---")
print(tokenized)

i have not_laughed so much in theater in years. only problem is that it was not_the intent of movie to make my throat raw from laughter.this movie is absolutely overflowing with bad cgi, absolutely terrible duologue, absolutely terrible *acting*, and enough geek references to make whole thing come off as nothing but complete cheese.as gamer and geek-type girl myself, i did recognize all of obvious game references in this movie as well as geek stuff that was just thrown into background as eye candy (the steamboy poster, t-shirts from thinkgeek.com and j-list.com), and that did not_redeem movie at all.the only thing that might have been good at all were ghost children type characters that were purposefully badly done in cgi to make it look like they were from game, and who were obviously stolen from japanese horror movies.to be honest, it was hilariously bad, and something i'd expect from midnight showing of made-for-tv b grade sci-fi channel movie. do not_expect more than that and you'l

Examine the outputs: The tokenizer returned three things:
- `input_ids` - this is a PyTorch tensor ([https://pytorch.org/docs/stable/tensors.html](https://pytorch.org/docs/stable/tensors.html)) with the indices of our tokens. PyTorch tensors are similar to numpy arrays. They hold data in a multidimensional array or matrix. The difference is that PyTorch tensors can be placed and modified on the GPU which greatly improves the speed of execution.
- `token_type_ids` - this tensor holds the information about the index of the sentence. This has to do with the classification objective from the original paper, where two sentences were given and the model had to predict if they are connected. Because we only included a single sentence, we have only zeros here. We will not be concerned with it in this lab.
- `attention_mask` - holds the mask that the model will use to determine if the tokens in the `input_ids` are the real tokens or *padding*. Padding is a technique used to ensure that all input sequences have the same length. BERT (like many other NLP models) process data in batches and requires each sequence in a batch to have the same length, so sequences that are shorter than the maximum sequence length in the batch are padded with special tokens. In this case, because we only inputted a single sentence, the mask contains only ones. Later you will see examples where this is not the case.

Let's see how exactly the sentence was tokenized and how we can retrieve the original text. Notice that some words have been split into multiple tokens (remember when we discussed sub-word tokenization in class?). Also pay attention to the added special tokens, namely `CLS` and `SEP`:

The `[CLS]` token is a special classification token added at the beginning of every input sequence. It stands for "classification" (daah!) and is used by BERT to aggregate information from the entire sequence. The final hidden state corresponding to this token (after passing through the transformer layers) is used as the aggregate sequence representation for classification tasks. We will use this later in the lab!

The `[SEP]` token is used to separate different segments or sentences within the input sequence. It stands for "separator" (daaah again!).

In [35]:
print(tokenized['input_ids'].shape)
print("---")
print(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0]))
print("---")
print(len(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0])))
print("---")
print(tokenizer.decode(tokenized['input_ids'][0]))
print("---")
print(tokenizer.decode(tokenized['input_ids'][0], skip_special_tokens=True))

torch.Size([1, 279])
---
['[CLS]', 'i', 'have', 'not', '_', 'laughed', 'so', 'much', 'in', 'theater', 'in', 'years', '.', 'only', 'problem', 'is', 'that', 'it', 'was', 'not', '_', 'the', 'intent', 'of', 'movie', 'to', 'make', 'my', 'throat', 'raw', 'from', 'laughter', '.', 'this', 'movie', 'is', 'absolutely', 'over', '##flow', '##ing', 'with', 'bad', 'c', '##gi', ',', 'absolutely', 'terrible', 'duo', '##logue', ',', 'absolutely', 'terrible', '*', 'acting', '*', ',', 'and', 'enough', 'g', '##eek', 'references', 'to', 'make', 'whole', 'thing', 'come', 'off', 'as', 'nothing', 'but', 'complete', 'cheese', '.', 'as', 'game', '##r', 'and', 'g', '##eek', '-', 'type', 'girl', 'myself', ',', 'i', 'did', 'recognize', 'all', 'of', 'obvious', 'game', 'references', 'in', 'this', 'movie', 'as', 'well', 'as', 'g', '##eek', 'stuff', 'that', 'was', 'just', 'thrown', 'into', 'background', 'as', 'eye', 'candy', '(', 'the', 'steam', '##boy', 'poster', ',', 't', '-', 'shirts', 'from', 'think', '##gee', '##

Tokenizer can process a list of sentences. This will create a batched output with tensor's first dimension corresponding to the batch size (the number of sentences we passed to the tokenizer). Examine the following cell and make sure it makes sense to you.

In [36]:
print(dataset['test'][0:3]['text'])
tokenized = tokenizer(dataset['test'][0:3]['text'], padding=True, return_tensors='pt')
print(tokenized)
print(tokenized['input_ids'].shape)
print(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0]))
print(len(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0])))
print(tokenizer.decode(tokenized['input_ids'][0]))
print(tokenizer.decode(tokenized['input_ids'][0], skip_special_tokens=True))

Token indices sequence length is longer than the specified maximum sequence length for this model (1209 > 512). Running this sequence through the model will result in indexing errors


['i have not_laughed so much in theater in years. only problem is that it was not_the intent of movie to make my throat raw from laughter.this movie is absolutely overflowing with bad cgi, absolutely terrible duologue, absolutely terrible *acting*, and enough geek references to make whole thing come off as nothing but complete cheese.as gamer and geek-type girl myself, i did recognize all of obvious game references in this movie as well as geek stuff that was just thrown into background as eye candy (the steamboy poster, t-shirts from thinkgeek.com and j-list.com), and that did not_redeem movie at all.the only thing that might have been good at all were ghost children type characters that were purposefully badly done in cgi to make it look like they were from game, and who were obviously stolen from japanese horror movies.to be honest, it was hilariously bad, and something i\'d expect from midnight showing of made-for-tv b grade sci-fi channel movie. do not_expect more than that and yo

<a name='e7'></a>
#### Exercise 7: Questions about the tokenizer

Answer the following questions:
- (1p) What is the size of the vocabulary?
- (2p) What are the special tokens apart from `[CLS]` and `[SEP]`? What are their functions?

--- YOUR ANSWERS HERE


#### Vocab size:

The vocab size is **28996** words

#### Tokens:

[PAD] = Padding token, used to make all sequences in a batch the same length. It is ignored by the attention mechanism using an attention mask and has its own embedding but does not carry semantic meaning. 

[UNK] = Unknown token, represents words that are not in the vocabulary 

[MASK] = Masking token, Used during masked language modeling (MLM) pretraining so the model learns to predict the masked word.

### 4.2 Loading the Model

In this section, we will load and examine the model. We will start with selecting the device we will place the model on. This will be a GPU (if one is available) or a CPU.

Google Colab offers free access to GPU, provided there is availability (also based on quotas which may vary based on your usage and the overall demand on Colab's resources). If you are working locally, then if you don't have a GPU, CPU will be selected. For the first parts of the assignment running on CPU might be okay but when we have to process the dataset a GPU will be necessary.

The following cell will select the device for us.

In [37]:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

Device: cpu


Now, let's load the model from huggingface and move it (slowly because it's heavy due to the large number of parameters) on the device from the previous cell (the methods `to()`).

In [38]:
model = transformers.AutoModel.from_pretrained(model_name)
print('loaded on device:', model.device)
model.to(device)
print('moved to device', model.device)
print(model)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: google-bert/bert-base-cased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


loaded on device: cpu
moved to device cpu
BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (

When loading the model you might have seen the warning about some unexpected weights. This means that the model on huggingface has some additional weights that were downloaded, but our model does not use them. In essence, you can load the same weights (as linked by our `model_name`) to load to different but related models. In our case those would be `BertForMaskedLM` or `BertForNextSentencePrediction` instead of our `BertModel`, which is loaded automatically as the `AutoModel`. Below is a way to load the weights into a different model.

In [39]:
# transformers.BertForMaskedLM.from_pretrained(model_name)

Next, let's use BERT model for inference. We will tokenize the first sentence of our dataset and pass it to the model. We set `output_hidden_states` to `True` in order to have access to the hidden states of the model. Those represent the latent representations after embedding and transformer layers.

In [40]:
tokenized = tokenizer(dataset['test'][0]['text'], padding=True, return_tensors='pt').to(device)
print(tokenized)
model_output = model(**tokenized, output_hidden_states=True)

{'input_ids': tensor([[  101,   178,  1138,  1136,   168,  3348,  1177,  1277,  1107,  5184,
          1107,  1201,   119,  1178,  2463,  1110,  1115,  1122,  1108,  1136,
           168,  1103,  7676,  1104,  2523,  1106,  1294,  1139,  2922,  7158,
          1121,  7053,   119,  1142,  2523,  1110,  7284,  1166, 12712,  1158,
          1114,  2213,   172,  5389,   117,  7284,  6434,  6862, 12733,   117,
          7284,  6434,   115,  3176,   115,   117,  1105,  1536,   176, 20059,
          7732,  1106,  1294,  2006,  1645,  1435,  1228,  1112,  1720,  1133,
          2335,  9553,   119,  1112,  1342,  1197,  1105,   176, 20059,   118,
          2076,  1873,  1991,   117,   178,  1225,  6239,  1155,  1104,  5119,
          1342,  7732,  1107,  1142,  2523,  1112,  1218,  1112,   176, 20059,
          4333,  1115,  1108,  1198,  6358,  1154,  3582,  1112,  2552, 13962,
           113,  1103,  5543,  9858, 14525,   117,   189,   118, 11710,  1121,
          1341, 15762,  1377,   119,  

Examine the next cell and make sure everything makes sense to you. Consult the [documentation](https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel.forward) in case of doubt.

In [41]:
print(list(model_output.keys()))
print()
print('pooler_output:')
print(type(model_output['pooler_output']))
print(model_output['pooler_output'].shape)
print()
print('hidden_states:')
print(type(model_output['hidden_states']))
print(len(model_output['hidden_states']))
print(type(model_output['hidden_states'][0]))
print(model_output['hidden_states'][0].shape)
print()
print('last_hidden_state:')
print(type(model_output['last_hidden_state']))
print(model_output['last_hidden_state'].shape)

['last_hidden_state', 'pooler_output', 'hidden_states']

pooler_output:
<class 'torch.Tensor'>
torch.Size([1, 768])

hidden_states:
<class 'tuple'>
13
<class 'torch.Tensor'>
torch.Size([1, 279, 768])

last_hidden_state:
<class 'torch.Tensor'>
torch.Size([1, 279, 768])


<a name='e8'></a>
#### Exercise 8: Questions about the Model

Examine the output of the previous cells. Answer the following questions:
- (1p) What is the number of transformer layers in this model?
- (1p) What is the dimension of the embeddings?
- (1p) What is the hidden size of the FFN in the transformer layer?
- (1p) What is the total number of parameters of the model (hint: check the `num_parameters()` method of the model)?
- (1p) How can you find the vocabulary size from the model?
- (1p) What is the length of the `hidden_states` in the output? Why?

--- YOUR ANSWERS HERE

**Number of transformer layers:**
The Model has 12 transformer layers. You can see it in: "(0-11): 12 x BertLayer" 

**Dimension of the Embedding:**
The Dimension of the emeddings is 768, shown in: word_embeddings: Embedding(28996, 768, ...) and also in the output shapes (..., 768).

**Size of the FFN in the transformer layer:**
The size of the FFN in the tranformer layer is 3072. Found through: model.config.intermediate_size


**Total Number of parameters:**
The total number of parameters is: 108310272

**How to find vocabulary size:** 
model.get_input_embeddings().weight.shape[0]

**Length of the hidden state in the output:** 
The lenght of the hidden state in the output is 13 because there is one tensor for embeddings before any transformer layers and 12 tensors for the outputs after each of the 12 transdormer layers. 

## 5. BERT Sentence Embeddings

Having the model loaded and ready we can work on obtaining the sentence embeddings. During the last lab, you averaged the token embeddings. This time we will start with something else. Remember the CLS token? Its hidden representation is often used for classification as a representation of the whole sentence. We will do exactly that.

But first, we have to tokenize the dataset using BERT tokenizer.

<a name='e9'></a>
#### Exercise 9: BERT tokenizing examples

(5p) Fill in the following function to embed the examples (passed as a parameter) using the tokenizer (also a parameter). The function will tokenize a batch of examples, but the tokenizer can handle that, if you remember from the previous section.

In [42]:
def tokenize_text_bert(examples, tokenizer):
    """
    Tokenizes the `sentence` column from the batch of examples and returns the whole output of the tokenizer.
    Args:
        examples: a batch of examples
        tokenizer: the BERT tokenizer

    Returns: the tokenized `sentence` column (returns the whole output of the tokenizer)

    """
    ### YOUR CODE HERE
    tokenized_sentence = None
    
    tokenized_sentence = tokenizer(examples['text'], padding=True, return_tensors='pt')


    ### YOUR CODE ENDS HERE
    return tokenized_sentence


In [43]:
dataset_tokenized_bert = dataset.map(tokenize_text_bert,
                                     fn_kwargs={'tokenizer': tokenizer},
                                     batched=True,
                                     remove_columns=dataset['train'].column_names,)
print(dataset_tokenized_bert)

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 20000
    })
    validation: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 25000
    })
})


<a name='e10'></a>
#### Exercise 10: BERT sentence embeddings by the CLS token

(5p) Implement the following function which calculates the sentence embeddings based on the model output (passed to the function as a parameter). It should take the embedding of the CLS token of last layer.

In [ ]:
def calculate_cls_embeddings(input_batch, model_output):
    """
    Calculates the sentence embeddings of a batch of sentences as the last-layer representation of the CLS token.
    Args:
        input_batch: tokenized batch of sentences (as returned by the tokenizer), contains `input_ids`, `token_type_ids`, and `attention_mask` tensors
        model_output: the output of the model given the `input_batch`, contains `last_hidden_state`, `pooler_output`, `hidden_states` tensors

    Returns: tensor of the hidden states of the CLS token (from the last layer) for each example in the batch

    """

    ### YOUR CODE HERE
    sentence_embeddings = None



    ### YOUR CODE ENDS HERE

    return sentence_embeddings

In [ ]:
text = "The weather is nice today."
tokenized = tokenizer(text, padding=True, return_tensors='pt').to(device)
print(tokenized)
model_output = model(**tokenized, output_hidden_states=True)
print(model_output['last_hidden_state'].shape)
sentence_embedding = calculate_cls_embeddings(tokenized, model_output)
print(sentence_embedding.shape)

In [ ]:
def embed_dataset(dataset, model, sentence_embedding_fn, batch_size=8):
    data_collator = transformers.DataCollatorWithPadding(tokenizer)
    data_loader = DataLoader(dataset, batch_size=batch_size, collate_fn=data_collator)
    sentence_embeddings = []
    with torch.no_grad():
        for batch in tqdm.tqdm(data_loader):
            batch.to(device)
            model_output = model(**batch, output_hidden_states=True)
            batch_sentence_embeddings = sentence_embedding_fn(batch, model_output)
            sentence_embeddings.append(batch_sentence_embeddings.detach().cpu())

    sentence_embeddings = torch.concat(sentence_embeddings, dim=0)
    return sentence_embeddings

In [ ]:
bert_cls_train = embed_dataset(dataset_tokenized_bert['train'], model, calculate_cls_embeddings)
print(bert_cls_train.shape)

bert_cls_valid = embed_dataset(dataset_tokenized_bert['validation'], model, calculate_cls_embeddings)
print(bert_cls_valid.shape)

In [ ]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
print('Training classifier...')
classifier.fit(bert_cls_train, y_train)

In [ ]:
print('BERT train')
pred_train = classifier.predict(bert_cls_train)
print(accuracy_score(y_train, pred_train))

print('BERT valid')
pred_valid = classifier.predict(bert_cls_valid)
print(accuracy_score(y_valid, pred_valid))

You can test the model on the evaluation metric of your choice:

In [ ]:
#### YOUR CODE HERE


#### YOUR CODE ENDS HERE

<a name='e11'></a>
#### Exercise 11: BERT Sentence embeddings by averaging tokens

(5p) Implement embedding sentences by averaging the hidden representations of tokens. Make sure to ignore the special and padding tokens. The padding tokens are indicated by the attention mask. You can find the other special tokens using the tokenizer's attributes such as `tokenizer.sep_token_id`. The function accepts the `layer` parameter. Typically, you would use the hidden representations of the last layer, it might be beneficial for some tasks to use previous layers or an averaged representations of multiple layers.

In [44]:
### YOUR CODE HERE

def calculate_sentence_embeddings(input_batch, model_output, layer=-1):
    """
    Calculates the sentence embeddings of a batch of sentences as a mean of token representations.
    The representations are taken from the layer of the index provided as a `layer` parameter.
    Args:
        input_batch: tokenized batch of sentences (as returned by the tokenizer), contains `input_ids`, `token_type_ids`, and `attention_mask` tensors
        model_output: the output of the model given the `input_batch`, contains `last_hidden_state`, `pooler_output`, `hidden_states` tensors
        layer: specifies the layer of the hidden states that are used to calculate sentence embedding

    Returns: tensor of the averaged hidden states (from the specified layer) for each example in the batch

    """
    attention_mask = input_batch['attention_mask']
    hidden_states = model_output['hidden_states'][layer]

    ### YOUR CODE HERE
    input_ids = input_batch['input_ids']

    device = hidden_states.device
    token_mask = attention_mask.bool().to(device)

    special_ids = [
        getattr(tokenizer, 'cls_token_id', None),
        getattr(tokenizer, 'sep_token_id', None),
        getattr(tokenizer, 'pad_token_id', None),
        getattr(tokenizer, 'mask_token_id', None)
    ]
    for sid in special_ids:
        if sid is not None:
            token_mask = token_mask & (input_ids.to(device) != sid)

    token_mask_float = token_mask.unsqueeze(-1).float()  # (B, S, 1)
    masked_hidden = hidden_states * token_mask_float     # zero-out excluded tokens

    denom = token_mask_float.sum(dim=1).clamp(min=1.0)   # (B, 1)
    sentence_embeddings = masked_hidden.sum(dim=1) / denom  # (B, H)


    ### YOUR CODE ENDS HERE

    return sentence_embeddings

### YOUR CODE ENDS HERE

We can test it here:


In [55]:
text = "The weather is nice today."
tokenized = tokenizer(text, padding=True, return_tensors='pt').to(device)
print(tokenized)
model_output = model(**tokenized, output_hidden_states=True)
print(model_output['last_hidden_state'].shape)
sentence_embedding = calculate_sentence_embeddings(tokenized, model_output)
print(sentence_embedding.shape)

{'input_ids': tensor([[ 101, 1109, 4250, 1110, 3505, 2052,  119,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}
torch.Size([1, 8, 768])
torch.Size([1, 768])


We will embed the sentences and evaluate the model on the `validation` subset.


In [ ]:
bert_sentence_train = embed_dataset(dataset_tokenized_bert['train'], model, calculate_sentence_embeddings)
print(bert_cls_train.shape)

bert_sentence_valid = embed_dataset(dataset_tokenized_bert['validation'], model, calculate_sentence_embeddings)
print(bert_cls_valid.shape)

In [ ]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
print('Training classifier...')
classifier.fit(bert_sentence_train, y_train)

In [ ]:
print('BERT train')
pred_train = classifier.predict(bert_sentence_train)
print(accuracy_score(y_train, pred_train))

print('BERT valid')
pred_valid = classifier.predict(bert_sentence_valid)
print(accuracy_score(y_valid, pred_valid))

Test the model on the evaluation metric of your choice:


In [ ]:
#### YOUR CODE HERE


#### YOUR CODE ENDS HERE

## 6. Testing all methods

In this last section, you will bering together all of what you have done so far in this lab. First, you will find the best classifier. Next, you will evaluate all the models you created so far.

<a name='e12'></a>
#### Exercise 12: Find the best classifier for the models

(5p) Basically, do what the title of the exercise says. Evaluate on the `validation` subset. Try at least two other classifiers (apart from the logistic regression). Comment on the results.

In [ ]:
#### YOUR CODE HERE


#### YOUR CODE ENDS HERE

--- YOUR ANSWERS HERE

<a name='e13'></a>
#### Exercise 13: Evaluating methods on the test set

(10p) Test the models you implemented on the test subset:
- Hand-crafted features,
- BOW,
- BERT model based on the CLS token.

You have the models trained already, so only do evaluation.

Evaluate the performance using the metric(s) of your choice. Make sure to discuss the results. Which model performed best? Is this what you expected?

In [ ]:
#### YOUR CODE HERE


### YOUR CODE ENDS HERE

--- YOUR ANSWERS HERE